-- wa-agent: queue-and-approve workflow for `assisted` mode (v0.8).
--
-- v0.5 introduced `mode: 'assisted'` — every AI turn is also recorded as an
-- `assisted_review` escalation for human spot-checks. But the AI reply still
-- went out immediately; humans could review AFTER the fact.
--
-- v0.8 closes the loop. When `Agent.reviewQueue` is set + `mode === 'assisted'`,
-- `reply.ai()` enqueues a `pending` row INSTEAD of calling `client.sendText`.
-- The human-review dashboard reads from this table; approving dispatches the
-- text (possibly edited) via the per-tenant Agent. Rejecting silently drops.
--
-- Apps with their own richer schema (psy-specific patient FKs, audit columns,
-- approval workflow state machines) point the framework at their table via
-- `tableName` + `columnMap` + `omitColumns` + `allowedExtraColumns` — same
-- pattern as `EscalationStore` and `ConsentStore`.
--
-- Columns:
--   id            — UUID generated by the framework.
--   whatsapp      — E.164 of the user whose AI turn is queued.
--   ai_text       — the original answer the LLM produced.
--   edited_text   — overrides ai_text on dispatch when set; NULL means "send the AI text".
--   status        — 'pending' | 'approved' | 'sent' | 'rejected'.
--                   The framework only WRITES 'pending' (enqueue) and 'sent'
--                   (dispatch). Apps move pending → approved | rejected via
--                   the dashboard. dispatchApprovedReviews picks up
--                   'approved' rows and flips them to 'sent' after the
--                   WhatsAppClient call.
--   wamid         — wamid of the inbound that triggered this turn. Lets
--                   handlers correlate with MessageLog rows.
--   trace_id      — pipeline trace correlation.
--   tenant_id     — multi-tenant scoping; single-tenant apps leave NULL.
--   thread_id     — AI thread id the answer belonged to.
--   created_at    — when the row was enqueued.
--   approved_at   — when an operator acked (NULL until approved).
--   approved_by   — operator identifier (free-form).
--   sent_at       — when the WhatsApp send completed (NULL until dispatched).

CREATE TABLE IF NOT EXISTS pending_reviews (
  id           TEXT PRIMARY KEY,
  whatsapp     TEXT NOT NULL,
  ai_text      TEXT NOT NULL,
  edited_text  TEXT,
  status       TEXT NOT NULL DEFAULT 'pending',
  wamid        TEXT,
  trace_id     TEXT,
  tenant_id    TEXT,
  thread_id    TEXT,
  created_at   TEXT NOT NULL DEFAULT (datetime('now')),
  approved_at  TEXT,
  approved_by  TEXT,
  sent_at      TEXT
);

CREATE INDEX IF NOT EXISTS idx_pending_reviews_status
  ON pending_reviews (status, created_at);
CREATE INDEX IF NOT EXISTS idx_pending_reviews_tenant
  ON pending_reviews (tenant_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_pending_reviews_whatsapp
  ON pending_reviews (whatsapp, status);
