-- wa-agent v0.9: per-call observability ledger for AIRouter.
--
-- Every LLM call routed through `AIRouter.route(...)` produces one row per
-- provider attempt — a single user-facing response may produce multiple
-- rows if the cascade walked several providers. Lets dashboards answer:
--
--   - "which provider answered (and how often vs the fallback)?"
--   - "what did we spend on LLM calls today, by task / tenant?"
--   - "p95 latency per provider, last 24h?"
--   - "rate-limit hits per provider, drilling down to error_message?"
--
-- Cost is stored as INTEGER micro-USD (1/1_000_000 USD) so aggregations
-- stay precise without floating-point drift over hundreds of thousands of
-- rows.
--
-- Apps with their own richer schema (already-existing observability tables,
-- different identity column, etc.) point AICallLedger at their table via
-- `tableName` + `columnMap` + `omitColumns` + `allowedExtraColumns` — same
-- pattern as `EscalationStore` / `ConsentStore` / `AgentReviewQueue`.
--
-- Columns:
--   id                  — UUID generated by the framework.
--   task                — caller-defined workload label ('classifier' / 'responder' / ...).
--   provider            — provider name as registered with the router.
--   model               — model slug the provider used (free-form string).
--   status              — 'success' | 'rate_limited' | 'timeout' | 'error' | 'parse_error' | 'skipped_open' | 'skipped_budget'.
--   http_status         — HTTP status code (NULL for transport-level failures).
--   latency_ms          — wall-clock time for the attempt.
--   tokens_in           — prompt tokens reported by the provider (NULL when unknown).
--   tokens_out          — completion tokens reported by the provider (NULL when unknown).
--   est_cost_micro_usd  — caller-supplied integer µUSD; framework does not estimate.
--   error_kind          — '429' | '5xx' | 'timeout' | 'network' | 'parse' | 'config'.
--   error_message       — truncated provider error text.
--   tenant_id           — multi-tenant scoping; single-tenant apps leave NULL.
--   whatsapp            — optional identity for per-user debug.
--   created_at          — when the row was recorded.

CREATE TABLE IF NOT EXISTS ai_call_log (
  id                 TEXT PRIMARY KEY,
  task               TEXT NOT NULL,
  provider           TEXT NOT NULL,
  model              TEXT,
  status             TEXT NOT NULL,
  http_status        INTEGER,
  latency_ms         INTEGER,
  tokens_in          INTEGER,
  tokens_out         INTEGER,
  est_cost_micro_usd INTEGER,
  error_kind         TEXT,
  error_message      TEXT,
  tenant_id          TEXT,
  whatsapp           TEXT,
  created_at         TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ai_call_log_provider_day
  ON ai_call_log (provider, created_at);
CREATE INDEX IF NOT EXISTS idx_ai_call_log_task_day
  ON ai_call_log (task, created_at);
CREATE INDEX IF NOT EXISTS idx_ai_call_log_status_day
  ON ai_call_log (status, created_at);
CREATE INDEX IF NOT EXISTS idx_ai_call_log_tenant_day
  ON ai_call_log (tenant_id, created_at);
