/**
 * full-bot — wa-agent showcasing every primitive in one Worker.
 *
 * Features:
 *   - First-contact OnboardingFlow (contact card + opt-in button + help text)
 *   - Tier check via HttpTierProvider + AccessGate
 *   - Premium-gated AI assistant via Azure OpenAI
 *   - Throttled Upsell (sendSmart picks full pitch vs reminder by funnel state),
 *     with a per-user payment link expanded via {{subscription_link}} tokens
 *   - UsageCounter logs blocked attempts for conversion-funnel analytics
 *   - PreferenceStore for delivery_mode (text / audio / both)
 *   - Auto-summarization of long answers (with "expand" button)
 *   - ReplyEnricher appends a UTM-tagged CTA footer to every AI answer
 *   - Audio messages: Whisper transcription → forward to AI
 *   - Daily devotional broadcast at 9am UTC (text + R2-cached TTS audio)
 *   - Daily yes/no re-engagement at noon UTC ("Did you read today?")
 *   - 21-day SequentialPlan with Done/Skip buttons (deliver at 6am UTC)
 *   - Slot-based content (one per slot, weighted, deduped) at 14h UTC
 *   - HybridSearch over a `docs` table (verses, FAQs, etc.)
 *   - `link <code>` command redeems a 6-digit code generated by the website
 *     to connect a web identity (Google sub / push endpoint) to this number
 *   - afterReply hook fires a daily-capped "Tip of the day" via
 *     RateCappedDispatcher (free-tier only, 1/day, 6h min-gap, quiet hours)
 *
 * Replace the "TODO" content with your own seed data.
 */
import { Hono } from 'hono';
import { AzureOpenAI } from 'openai';
import {
	Agent,
	mountWebhook,
	OpenAIAssistant,
	Summarizer,
	Transcriber,
	Broadcast,
	ReEngagement,
	SequentialPlan,
	SlotDelivery,
	R2Cache,
	AzureTTS,
	stripMarkdown,
	OnboardingFlow,
	HttpTierProvider,
	AccessGate,
	Upsell,
	UsageCounter,
	PreferenceStore,
	definePreference,
	HybridSearch,
	WhatsAppClient,
	LLMIntentClassifier,
	PolicyGate,
	defaultPipeline,
	AuditEmitter,
	createUtmTagger,
	HttpPaymentLinkProvider,
	expandTokens,
	LayeredReplyEnricher,
	AccountLinkStore,
	matchLinkCommand,
	RateCappedDispatcher,
	QuietHours,
	honoRateLimit,
	KvRateLimitStore,
	RateLimit,
	EscalationStore,
	SlackNotifier,
	LLMCostCalculator,
	ConsentStore,
} from 'wa-agent';

// Typed preference for delivery format
const deliveryMode = definePreference('delivery_mode', 'both', ['text', 'audio', 'both']);

let app, agent;

function init(env) {
	if (app) return;
	app = new Hono();

	const azure = new AzureOpenAI({
		endpoint: env.AZURE_OPENAI_ENDPOINT,
		apiKey: env.AZURE_OPENAI_API_KEY,
		apiVersion: env.AZURE_API_VERSION,
		deployment: env.AZURE_MODEL_DEPLOYMENT,
	});

	// Pluggable tier check (free / premium / lifetime) → AccessGate
	const tierProvider = new HttpTierProvider({
		baseUrl: env.BILLING_API_URL,
		token: env.BILLING_API_TOKEN,
	});

	// Per-user upgrade link, fetched lazily and expanded into outbound
	// templates via the `{{subscription_link}}` token.
	const paymentLinks = new HttpPaymentLinkProvider({
		baseUrl: env.BILLING_API_URL,
		token: env.BILLING_API_TOKEN,
	});

	// One UTM tagger for the whole bot — all outbound URLs go through it so
	// GA4 / your analytics correctly attribute the chat channel.
	const tagWa = createUtmTagger({ source: 'whatsapp' });

	// Build a WhatsAppClient once and reuse for OnboardingFlow + Upsell.
	// The Agent will build an equivalent internal client from the same config.
	const client = new WhatsAppClient({ endpoint: env.META_WA_ENDPOINT, token: env.META_WA_TOKEN });

	const onboarding = new OnboardingFlow({
		client,
		welcomeBody: ({ name }) => `Hi ${name || 'there'}! Tap below to start.`,
		helpText: 'Type "help" any time to see what I can do.',
	});

	const assistant = new OpenAIAssistant({ client: azure, assistantId: env.ASSISTANT_ID });
	const summarizer = new Summarizer({ client: azure, model: 'gpt-4o-mini' });

	// AI is premium-only; cap-free users hit the gate and see the Upsell.
	const gate = new AccessGate({ tierProvider, allowedTiers: ['premium', 'lifetime'], freeMessageLimit: 0 });

	// --- Pipeline: intent → policy → LLM → audit ---
	// Bots opt in by passing `pipeline` to the Agent. Custom intent enum +
	// one custom guard ("block messages containing a phone number") drive
	// the example. Real bots wire `classify` to Vercel AI SDK / OpenAI / etc.
	const INTENTS = ['question', 'booking', 'cancel', 'other'];
	const classifier = new LLMIntentClassifier({
		intents: INTENTS,
		fallback: 'other',
		classify: async (text) => {
			// Stub: keyword classifier so the example runs without an LLM call.
			// Replace with `generateObject({ model, schema: z.object({...}), prompt: text })`.
			const t = text.toLowerCase();
			if (/book|agend/.test(t)) return { intent: 'booking', confidence: 0.85 };
			if (/cancel/.test(t)) return { intent: 'cancel', confidence: 0.85 };
			if (/\?$/.test(t)) return { intent: 'question', confidence: 0.7 };
			return { intent: 'other', confidence: 0.5 };
		},
	});

	const phoneRegex = /\+?\d[\d\s().-]{8,}/;
	const policy = new PolicyGate({
		accessGate: gate,
		predicates: [
			// Block messages containing a phone number — they belong with a human.
			(ctx) =>
				phoneRegex.test(ctx.text)
					? { proceed: false, reason: 'contains_phone_number', action: 'escalate' }
					: null,
		],
	});

	// AI-reply enricher: append a tagged CTA footer to every assistant
	// answer. Runs on both the long answer and the summary, so users see the
	// footer regardless of length. First layer skips when the answer already
	// contains a docs link (idempotent on re-runs / forwarded messages).
	const replyEnricher = new LayeredReplyEnricher({
		layers: [
			// Skip if there's already a CTA — keeps the enricher idempotent.
			(answer) => (answer.includes('utm_source=whatsapp') ? answer : answer),
			(answer) =>
				`${answer.trim()}\n\n_More tips:_ ${tagWa('https://example.com/help', 'ai_reply')}`,
		],
	});

	// v0.6: per-user opt-in for AI processing. The welcome flow already
	// shows a `consent_ai_processing` button; the button handler below
	// records the grant. The AI-fallback path checks `consents.has(...)`
	// before billing the user for an LLM turn.
	const consents = new ConsentStore({ db: env.DB });

	// Escalation log + optional Slack fan-out. The pipeline's `PolicyGate`
	// returns `action: 'escalate'` for messages containing a phone number;
	// the Agent records them automatically (with the policy reason +
	// traceId) before short-circuiting. urgency='medium' is the default.
	const escalationStore = new EscalationStore({
		db: env.DB,
		notifier: env.SLACK_ESCALATION_WEBHOOK
			? new SlackNotifier({ webhookUrl: env.SLACK_ESCALATION_WEBHOOK })
			: null,
		notifyAtOrAbove: 'medium',
	});

	agent = new Agent({
		whatsapp: {
			endpoint: env.META_WA_ENDPOINT,
			token: env.META_WA_TOKEN,
			verifyToken: env.META_WH_TOKEN,
			appSecret: env.META_APP_SECRET,
		},
		db: env.DB,
		ai: assistant,
		summarizer,
		tierProvider,
		onboarding,
		replyEnricher,
		escalationStore,
		events: { env }, // env.EVENTS Analytics Engine binding (or no-op if absent)
		pipeline: defaultPipeline({
			ai: assistant,
			summarizer,
			intent: classifier,
			policy,
			emit: () => Promise.resolve(), // wired by Agent below
			modelName: 'openai-assistant',
		}),
	});
	// Hand the Agent's bound emit to the pipeline's audit step so events flow
	// through the same Analytics Engine dataset as the rest of the framework.
	agent.pipeline.replaceStep('audit', new AuditEmitter({ emit: agent.emit }));

	const transcriber = new Transcriber({ client: azure });
	const usage = new UsageCounter({ db: agent.db });
	const prefs = new PreferenceStore({ db: agent.db });

	// Per-turn LLM cost calculator. Configured in BRL with a fixed FX rate
	// (refresh from your accounting source in production). Pairs with
	// UsageCounter so per-user cost rolls up via the existing analytics
	// queries — feature='ai_cost_brl', stored as a string under the `key`
	// column so daily aggregation can sum it.
	const costCalculator = new LLMCostCalculator({
		currency: 'BRL',
		fxRate: 5.5,
		decimals: 4,
		fallbackModel: 'gpt-4o-mini',
	});

	const upsell = new Upsell({
		client,
		leads: agent.leads,
		funnelState: 'CHECKOUT',
		pitch: 'Subscribe to keep chatting with the AI assistant. Free features stay free.',
		ctaText: 'Subscribe',
		// Resolve a per-user payment link via the provider, then tag the URL.
		// Returning null falls back to Upsell's default behavior.
		ctaUrl: async (whatsapp) => {
			const link = await paymentLinks.getPaymentLink({ whatsapp, campaign: 'upsell_cta' });
			return link ? tagWa(link, 'upsell_cta') : null;
		},
		video: env.PITCH_VIDEO_URL ? { url: env.PITCH_VIDEO_URL, caption: 'See how it works' } : null,
		reminder: { pitch: 'Tap below to subscribe — free features (verses, plans, devotionals) stay free.' },
	});

	// Account linking — the website's /me page issues a 6-digit code; the
	// user types `link <code>` here and we map their web identity to this
	// WhatsApp number. Allowlist matches what the website's identity_kind
	// column writes; codes outside it are refused (defense-in-depth).
	const accountLinks = new AccountLinkStore({
		db: agent.db,
		allowedIdentityKinds: ['google_sub', 'push_endpoint'],
	});

	// Opportunistic "Tip of the day" after each reply: free-tier only, at
	// most 1/day, 6h min-gap, never during quiet hours.
	const tipQuietHours = new QuietHours({ start: '22:00', end: '06:00', timezone: 'UTC' });
	const tips = new RateCappedDispatcher({
		counter: usage,
		feature: 'reactive_tip',
		dailyMax: 1,
		minGapSeconds: 6 * 3600,
		quietHours: tipQuietHours,
	});

	// ---- Commands ----
	agent.command(['help', 'h', '?'], async ({ reply }) => {
		await reply.text(helpText);
	});

	agent.command(['preferences', 'configurar'], async ({ reply }) => {
		await reply.buttons({
			body: 'How would you like to receive content?',
			buttons: [
				{ id: 'pref_mode_text', title: '📝 Text only' },
				{ id: 'pref_mode_audio', title: '🎧 Audio only' },
				{ id: 'pref_mode_both', title: '✨ Both' },
			],
		});
	});

	// `upgrade` — demonstrates expandTokens with {{subscription_link}}.
	// The token resolver only runs if the placeholder is actually present
	// in `template`, so a broken billing service doesn't block the command.
	agent.command(['upgrade', 'plans-pro'], async ({ user, reply }) => {
		const template = 'Premium unlocks unlimited AI replies and audio.\n\nUpgrade here: {{subscription_link}}';
		const body = await expandTokens(template, {
			'{{subscription_link}}': async () => {
				const link = await paymentLinks.getPaymentLink({ whatsapp: user.whatsapp, campaign: 'manual_upgrade' });
				return link ? tagWa(link, 'manual_upgrade') : null;
			},
		});
		await reply.text(body);
	});

	agent.command(['plan', 'plans'], async ({ user, reply }) => {
		const plans = new SequentialPlan({ db: agent.db });
		const enrolled = await plans.getActiveEnrollment(user.whatsapp);
		if (enrolled) {
			await reply.text(`You're on day ${enrolled.currentDay} of "${enrolled.title}".`);
			return;
		}
		const list = await plans.listActivePlans();
		if (!list.length) {
			await reply.text('No plans available.');
			return;
		}
		await reply.text(list.map((p, i) => `${i + 1}. ${p.title} — ${p.durationDays} days`).join('\n'));
		await reply.buttons({
			body: 'Pick a plan to start:',
			buttons: list.slice(0, 3).map((p) => ({ id: `plan_enroll_${p.id}`, title: p.title.slice(0, 17) })),
		});
	});

	// ---- Search before AI: hybrid lookup against a `docs` table ----
	const search = new HybridSearch({ db: agent.db, contentTable: 'docs', searchColumns: ['title', 'body'] });

	// ---- Default text handler: link redeem → search → tier-gate → AI ----
	agent.onText(async ({ text, inbound, user, reply }) => {
		// `link 123456` / `linkar 123456` / `vincular 123456` / `connect 123456`
		// — short-circuit before any AI work. CommandRouter does exact-match,
		// so the multi-word command lives in the fallback.
		const code = matchLinkCommand(text);
		if (code) {
			if (accountLinks.recordRedeemAttempt(user.whatsapp)) {
				await reply.text('⏳ Too many attempts. Try again in an hour.');
				return;
			}
			const r = await accountLinks.redeem(user.whatsapp, code);
			if (r.ok) {
				await reply.text(`✅ Connected! Your progress now shows on ${tagWa('https://example.com/me', 'account_link')}.`);
			} else {
				await reply.text(`❌ ${r.reason.replace(/_/g, ' ')}. Generate a new code at https://example.com/me.`);
			}
			return;
		}

		// Audio: transcribe first
		let prompt = text;
		if (inbound.type === 'audio' && inbound.audioId) {
			// Premium-only: don't pay Whisper for free users.
			const access = await gate.check(user.whatsapp);
			if (!access.allowed) {
				await usage.record(user.whatsapp, 'audio_gate_blocked');
				await reply.text('Audio messages need a subscription. Send text and I\'ll respond.');
				await upsell.sendSmart(user.whatsapp);
				return;
			}
			const stream = await agent.client.downloadMedia(inbound.audioId);
			prompt = (await transcriber.transcribe(stream)) || '';
		}
		if (!prompt) {
			await reply.text('Sorry, I could not understand that.');
			return;
		}

		// 1. Try local search first (free for everyone)
		const hits = await search.search(prompt, { limit: 1 });
		if (hits.length) {
			await reply.text(hits[0].body);
			return;
		}

		// 2. AI (premium only)
		const access = await gate.check(user.whatsapp);
		if (!access.allowed) {
			await usage.record(user.whatsapp, 'ai_gate_blocked');
			await upsell.sendSmart(user.whatsapp);
			return;
		}

		// 3. ConsentStore gate (v0.6) — make sure the user opted in to AI
		// processing. The opt-in button taps `consent_ai_processing` (handled
		// below) record the grant. Without consent we route them through the
		// welcome flow instead of billing the LLM.
		if (!(await consents.has(user.whatsapp, 'ai_processing'))) {
			await reply.text(
				'Antes de seguir, preciso que você aceite o uso de IA. Toque no botão acima ou digite "ajuda".',
			);
			return;
		}

		await reply.markRead();
		const session = await agent.session.get(user.whatsapp);
		await reply.ai(prompt, { threadId: session?.threadId });
	});

	// ---- Buttons ----
	// v0.6: opt-in for AI processing. The welcome flow's "Quero Conversar"
	// button has id `consent_ai_processing`; this handler records the grant
	// and unlocks the AI fallback in onText above.
	agent.button('consent_ai_processing', async ({ user, inbound, reply }) => {
		await consents.grant(user.whatsapp, 'ai_processing', {
			evidence: inbound.wamid ?? 'consent_ai_processing_button',
		});
		await reply.text('Obrigado! Manda sua dúvida que eu respondo.');
	});

	agent.buttonPrefix('expand_', async ({ suffix, log, reply }) => {
		const row = await log.byWamid(suffix);
		if (row?.response) await reply.text(row.response);
	});

	agent.buttonPrefix('pref_mode_', async ({ user, suffix, reply }) => {
		const ok = await deliveryMode.set(prefs, user.whatsapp, suffix);
		await reply.text(ok ? `✓ Saved: ${suffix}` : 'Could not save preference.');
	});

	agent.buttonPrefix('plan_enroll_', async ({ user, suffix, reply }) => {
		const plans = new SequentialPlan({ db: agent.db });
		await plans.enroll(user.whatsapp, parseInt(suffix, 10));
		await reply.text('Enrolled! Day 1 arrives tomorrow morning.');
	});

	agent.buttonPrefix('plan_done_', async ({ user, suffix, reply }) => {
		const [planId, day] = suffix.split('_').map(Number);
		const plans = new SequentialPlan({ db: agent.db });
		const r = await plans.markDone(user.whatsapp, planId, day);
		await reply.text(r.completed ? 'Plan complete! 🎉' : `Day ${day} done. See you tomorrow.`);
	});

	agent.buttonPrefix('plan_skip_', async ({ user, suffix, reply }) => {
		const [planId, day] = suffix.split('_').map(Number);
		const plans = new SequentialPlan({ db: agent.db });
		const r = await plans.skipDay(user.whatsapp, planId, day);
		await reply.text(r.completed ? 'Plan complete!' : `Skipped day ${day}.`);
	});

	// ---- ReEngagement answers ----
	const reading = new ReEngagement({
		client: agent.client,
		db: agent.db,
		topicId: 1,
		question: { body: 'Did you read your devotional yesterday?', yesLabel: 'Yes ✅', noLabel: 'No ❌' },
	});
	agent.buttonPrefix('engagement_1_', async ({ user, buttonId, reply }) => {
		await reading.recordAnswer(user.whatsapp, buttonId);
		const week = await reading.weekProgress(user.whatsapp);
		const summary = week.map((d) => (d.answer === 'a' ? '✅' : d.answer === 'b' ? '❌' : '⬜')).join(' ');
		await reply.text(`Got it!\nThis week: ${summary}`);
	});

	// ---- afterReply: opportunistic free-tier nudge ----
	// Runs after every successful dispatch. The cap/gap/quiet-hours guards
	// inside RateCappedDispatcher mean the user never sees more than one
	// tip per day, and the send is skipped silently when the conditions
	// aren't met. Premium users are excluded explicitly.
	agent.afterReply(async (ctx) => {
		if (!ctx.user?.whatsapp || ctx.isFirstContact) return;
		const tier = ctx.tier ? await ctx.tier.getTier(ctx.user.whatsapp) : { tier: 'free' };
		if (tier.tier !== 'free') return;
		await tips.tryDispatch(ctx.user.whatsapp, async () => {
			return await ctx.client.sendText(
				ctx.user.whatsapp,
				`💡 Tip: type "plans" to start a 21-day plan, or "upgrade" to unlock unlimited AI.`,
			);
		});
	});

	// ---- Cron jobs ----
	agent.cron('0 9 * * *', async ({ env }) => {
		// Daily devotional + audio (respects delivery_mode preference per-user)
		const today = await env.DB.prepare(`SELECT id, content, audio_url FROM devotional WHERE date = date('now')`).first();
		if (!today) return;

		// Lazily generate audio if missing
		if (!today.audio_url && env.TTS_BUCKET && env.TTS_PUBLIC_HOST) {
			const tts = new AzureTTS({ key: env.AZURE_SPEECH_KEY, region: env.AZURE_SPEECH_REGION, voice: 'en-US-AriaNeural', language: 'en-US' });
			const cache = new R2Cache({ bucket: env.TTS_BUCKET, publicHost: env.TTS_PUBLIC_HOST });
			const { url } = await cache.getOrCreate(`devotional/${new Date().toISOString().slice(0, 10)}.mp3`, async () => ({
				body: await tts.synthesize(stripMarkdown(today.content)),
				contentType: 'audio/mpeg',
			}));
			await env.DB.prepare(`UPDATE devotional SET audio_url = ? WHERE id = ?`).bind(url, today.id).run();
			today.audio_url = url;
		}

		const broadcast = new Broadcast({ client: agent.client, db: agent.db, channel: 'devotional' });
		await broadcast.run({
			send: async ({ whatsapp }) => {
				const mode = await deliveryMode.get(prefs, whatsapp);
				let ok = true;
				if (mode === 'text' || mode === 'both') {
					ok = await agent.client.sendText(whatsapp, today.content);
				}
				if (ok && today.audio_url && (mode === 'audio' || mode === 'both')) {
					await agent.client.sendAudioUrl(whatsapp, { url: today.audio_url });
				}
				return ok;
			},
		});
	});

	agent.cron('0 12 * * *', async () => {
		const broadcast = new Broadcast({ client: agent.client, db: agent.db, channel: 'engagement_reading' });
		await broadcast.run({ send: ({ whatsapp }) => reading.ask(whatsapp) });
	});

	agent.cron('0 6 * * *', async () => {
		// Sequential plan delivery
		const plans = new SequentialPlan({ db: agent.db });
		await plans.autoAdvanceStale();
		const users = await plans.usersForDelivery();
		for (const u of users) {
			const day = await plans.getDay(u.planId, u.currentDay);
			if (!day) continue;
			await agent.client.sendText(u.whatsapp, `📖 Day ${u.currentDay}/${u.durationDays} — ${day.title}\n\n${day.content}`);
			await agent.client.sendButtons(u.whatsapp, {
				body: 'When you finish, let me know:',
				buttons: [
					{ id: `plan_done_${u.planId}_${u.currentDay}`, title: '✅ Done' },
					{ id: `plan_skip_${u.planId}_${u.currentDay}`, title: '⏭ Skip' },
				],
			});
			await plans.markDelivered(u.whatsapp, u.planId, u.currentDay);
		}
	});

	agent.cron('0 14 * * *', async () => {
		// Slot-based delivery (afternoon tip/ad)
		const slot = new SlotDelivery({ db: agent.db });
		const users = await slot.usersForSlot('afternoon');
		for (const u of users) {
			const item = await slot.pickForUser(u.whatsapp);
			if (!item) continue;
			if (item.cta_url && item.cta_text) {
				await agent.client.sendCtaUrl(u.whatsapp, { body: item.body, displayText: item.cta_text, url: item.cta_url });
			} else {
				await agent.client.sendText(u.whatsapp, item.body);
			}
			await slot.recordImpression(u.whatsapp, item.id, 'afternoon');
		}
	});

	// Webhook rate limit (v0.4) — 60 hits/minute per IP × path. Registered
	// BEFORE mountWebhook so it runs before the signature check; cheap
	// reject for floods that would otherwise cost a DB read per hit.
	app.use(
		'/wa/webhook',
		honoRateLimit(
			new RateLimit({
				store: new KvRateLimitStore({ kv: env.KV, prefix: 'rl:full-webhook' }),
				windowSeconds: 60,
				max: 60,
			}),
		),
	);

	// Admin cost-estimate endpoint (v0.4) — quick demo of LLMCostCalculator
	// against an arbitrary model + token counts. In production this would
	// sit behind basic-auth like the dashboard, and read actual usage from
	// the LLM SDK callback or a per-tenant ledger.
	app.get('/admin/cost', (c) => {
		const model = c.req.query('model') || 'gpt-4o-mini';
		const input = parseInt(c.req.query('in') || '0', 10);
		const output = parseInt(c.req.query('out') || '0', 10);
		const r = costCalculator.compute(model, { inputTokens: input, outputTokens: output });
		return c.json(r);
	});

	mountWebhook(agent, app);
}

const helpText = `Hi! I'm a wa-agent demo bot.
- Type anything to chat (premium)
- Send a verse reference / question for free lookup
- "plan" — see content plans
- "configurar" — set delivery preference
- "link <code>" — connect your account from example.com/me
- "upgrade" — get your subscription link
- "stop" — opt out`;

export default {
	fetch: (req, env, ctx) => {
		init(env);
		return app.fetch(req, env, ctx);
	},
	scheduled: (event, env, ctx) => {
		init(env);
		return agent.scheduled(event, env, ctx);
	},
};
